from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1331, 818)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/keyboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget {\nbackground-color: #4682B4;\n}\nQPushButton {\n"
                                 "background-color: transparent;\nborder: none;\nborder-width:1px;\n"
                                 "border-radius:25px;\nborder-color: none;\n}\nQPushButton:hover {\n"
                                 "background-color: #66b8ff;\n}\nQPushButton:pressed {\nbackground-color: #4682B4;\n"
                                 "}\nQLineEdit {\nborder: 5px solid rgb(52, 65, 255);}\n")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 70, 571, 141))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(56)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(52, 65, 255);")
        self.label.setObjectName("label")
        self.lbl_out = QtWidgets.QLabel(self.centralwidget)
        self.lbl_out.setGeometry(QtCore.QRect(120, 280, 1081, 51))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_out.setFont(font)
        self.lbl_out.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_out.setText("")
        self.lbl_out.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_out.setObjectName("lbl_out")
        self.line_in = QtWidgets.QLineEdit(self.centralwidget)
        self.line_in.setGeometry(QtCore.QRect(120, 370, 1081, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.line_in.setFont(font)
        self.line_in.setStyleSheet("color: #d4d4d4;")
        self.line_in.setText("")
        self.line_in.setAlignment(QtCore.Qt.AlignCenter)
        self.line_in.setObjectName("line_in")
        self.btn_re = QtWidgets.QPushButton(self.centralwidget)
        self.btn_re.setGeometry(QtCore.QRect(570, 540, 201, 141))
        self.btn_re.setStyleSheet("")
        self.btn_re.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon (1) (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_re.setIcon(icon1)
        self.btn_re.setIconSize(QtCore.QSize(200, 220))
        self.btn_re.setObjectName("btn_re")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 510, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(52, 65, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 560, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(52, 65, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 610, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(52, 65, 255);")
        self.label_4.setObjectName("label_4")
        self.log = QtWidgets.QLineEdit(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(40, 70, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.log.setFont(font)
        self.log.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.log.setObjectName("log")
        self.pswrd = QtWidgets.QLineEdit(self.centralwidget)
        self.pswrd.setGeometry(QtCore.QRect(40, 110, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pswrd.setFont(font)
        self.pswrd.setObjectName("pswrd")
        self.sign_up = QtWidgets.QPushButton(self.centralwidget)
        self.sign_up.setGeometry(QtCore.QRect(40, 150, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sign_up.setFont(font)
        self.sign_up.setObjectName("sign_up")
        self.sign_in = QtWidgets.QPushButton(self.centralwidget)
        self.sign_in.setGeometry(QtCore.QRect(40, 190, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sign_in.setFont(font)
        self.sign_in.setObjectName("sign_in")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KeyBoard Simulator"))
        self.label.setText(_translate("MainWindow", "Typing Simulator"))
        self.label_2.setText(_translate("MainWindow", "Time: "))
        self.label_3.setText(_translate("MainWindow", "Wpm: "))
        self.label_4.setText(_translate("MainWindow", "Accuracy: "))
        self.log.setPlaceholderText(_translate("MainWindow", "Login..."))
        self.pswrd.setPlaceholderText(_translate("MainWindow", "Password..."))
        self.sign_up.setText(_translate("MainWindow", "Sign up"))
        self.sign_in.setText(_translate("MainWindow", "Sign in"))
